# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "schedule-state-bucket"
    encrypt = true
    key     = "prod/network/terraform.tfstate"
    region  = "eu-central-1"
  }
}
